### ISSUE TITLE
Allow recursive update of parents

### ISSUE THREAD

**Issue by joachimdalen** [joachimdalen/azdevops-auto-state#1]
When defining a new rule there should be an option to enable recursive update. This recursive update would be used to update item all the way up the chain. 

Consider the following structure of work items:

- Epic (New)
  -  Feature (New)
     - User Story (New)
        - Task (New)
        - Task (New)

When updating the lowest Task we should be able to update the state all the way up to the Epic. For this to work, rules should be defined for each individual level (3 different rules for this scenario)

TODO: 

- [x] Extend rule with new property for processing parent
- [x] Add configuration to `rule-modal`
- [x] Add new column to admin table
- [x] Add processing in RuleProcessor
- [x] Add documentation
   - [x] Usage of `Children lookup`
   - [x] Usage of `Process parent`
- [x] Update screenshots
- [x] Update tests

**Comment by justinwallin** [comment]
Has this been deployed to a production build yet?  I cannot create a rule so that when 1 of many children (User Story) move from a "New" to "Active" state, that the parents (Feature & Epic both) are updated to "Active".  In my example ALL children user stories for the feature have to be "Active" before the parents will update successfully.  Any suggestions?  I feel like I have something wrong in my rule creation, but cannot figure it out.

**Comment by joachimdalen** [comment]
Hi @justinwallin 
Yes, this was deployed in version [1.1.0](https://github.com/joachimdalen/azdevops-auto-state/blob/master/CHANGELOG.md#110-2022-01-05). I will look into your case and see if there is a bug or possibly just a configuration error.

**Comment by joachimdalen** [comment]
I just checked, and the extension seems to work fine:

With this as the starting backlog:
![image](https://user-images.githubusercontent.com/15696189/158060648-f6fd9913-ca9d-48cf-8caf-e68614fa2365.png)

and the following rules configured:
![image](https://user-images.githubusercontent.com/15696189/158060670-e6e2110e-08ff-46da-ae82-6cd6e75c8fb2.png)

after setting `GH User Story 2-3` to `Active`, I end up with the following:
![image](https://user-images.githubusercontent.com/15696189/158060690-61f78a20-19dc-4580-bdb5-bc932906de80.png)


NOTE: Check that you don't have the `Children lookup` option enabled. This will check that all children of the parent have a rule that matches the `target state` before it updates the parent. That option is mostly used when wanting to close an item, and prevent it from being closed if not all children are closed.

**Comment by justinwallin** [comment]
Thanks for the quick response.  My setup looks exactly like what you have,
but I cannot get it to work.  Please note I am not a developer, and just a
user of this extension.  Screenshots of my setup are as follows:

[image: image.png]
Initial setup:
[image: image.png]
When I change "User Story 2" under "Test Feature 2" to "Active", Save the
work item and refresh my query the result is this:
[image: image.png]

If I change User Story 2 under Feature 2 to Active, select save and refresh
the query, the result is shown below.  I seem to have all children to be
set to Active before the Parent is updated.
[image: 0a586054-3ad9-4f91-bc3b-90d2cd504f16.png]
Is there something else that I need to download and install to get your
updates by chance?

I really appreciate any help or suggestions.  I need to step away for a bit
but will check back after while.

Thanks again,
Justin

**Comment by joachimdalen** [comment]
Hi again, 

It's strange that the same setup does not work for you. Replying to issues using email does not include the attached images. Would you be able to upload them using the GitHub website? Alternatively you can resend the email to `jd.ado.extensions` (at) `protonmail.com`, then we can take it from there.

There is no need for any additional downloads or installations for this work.

**Comment by joachimdalen** [comment]
Thank you for the email, it allowed me to test directly using your scenario. I tested at my side, and it seems to work here.. there are a few more details I need to be sure.

From what view are you updating the state of the work item?
1. Using the preview pane that opens to the right or bottom in the Query view
2. Using the "..." and the modal (this one) 
![image](https://user-images.githubusercontent.com/15696189/158063874-b4a5a3ae-b026-4eb0-a483-6d8d8e9f1b3a.png)
3. Opening the full work item form (this one)
![image](https://user-images.githubusercontent.com/15696189/158063922-54672611-c999-48c0-98f2-811afb784e88.png)

 Based on my tests, only option 1 and 3 will work. This is due to limitations in Azure DevOps. 

Due to some other limitations and the way this extension is built, there might be a few seconds delay in updating all the work items. Could you try to update the work item, and wait a few seconds before navigating back to the query results?

**Comment by justinwallin** [comment]
I've been updating my user story in the preview pane to the right of the
query one at a time (as you describe in step 1 above), selecting save, and
then re-running the query (sometimes quickly, but have also waited for
upwards of 30 seconds to re-run again to see if it was a timing issue.

When resetting my states/tests back to new to try additional configs of the
rule, I have been selecting all the workitems in the query, right-clicking,
& editing the states back to new as you show in step 2 from above.

I'm really puzzled...

**Comment by joachimdalen** [comment]
Hmm.. okay, yeah, I'm not really sure what is going on then. I will dig into some code later when I get time and see if I missed something. I will keep you posted when I've had time to do this.

One last thing that could be useful to check, do you experience the same issue if you update the user story from the backlogs view and not inside a query result?

**Comment by justinwallin** [comment]
Bingo! Updating from the backlog view works perfectly!

**Comment by joachimdalen** [comment]
Ahh.. Then I suspect there is something funky with the query results view (which could be related to this: #38), but I'll do some more investigation into it.

**Comment by justinwallin** [comment]
Thanks for the help on this!  Appreciate it!  I should be able to move on
with my testing now and eventually build some rules out for production use
on my side.

**Comment by joachimdalen** [comment]
Great! Happy to help. As said, I'll look more into this and see if I can also get it working on the query results view.
Please let me know if you experience any other issues :)
