### ISSUE TITLE
Do not set "assigned to" value after changing state.

### ISSUE THREAD

**Issue by kameelyan** [joachimdalen/azdevops-auto-state#50]
When the state is being set via the extensions, all of the parents assigned to values are being set to the user who changed the child state. In our use case, we're going all the way from the Task level to the Epic level up the tree. Is there any way to prevent that change from taking place?

**Comment by joachimdalen** [comment]
Hi there!

"Assigned to" is one of the dependent fields on the State field when activating a work item. That means that when you make changes to a work item and change it to an active state, DevOps updates this field in the background.

I might be able to override this behavior, will take a look into it and get back to you.

**Comment by joachimdalen** [comment]
Hi again!

Checked into this. I will add an option to the rules where you can specify that it will keep the old value of Assignee when updating rules.

**Comment by joachimdalen** [comment]
I just released a new option in `v1.3.0` that should fix this. It is an option that needs to be set on the rules. If a work item does not have any assignee, it will be left as unassigned else it will keep the current assignee. 

You can find it under the `Options` tab when editing the rule.
![image](https://user-images.githubusercontent.com/15696189/172038069-725fad4a-ed67-43f3-970c-75dea23d7d44.png)
