### ISSUE TITLE
It's not clear how to activate the extension

### ISSUE THREAD

**Issue by ruksarjk** [joachimdalen/azdevops-auto-state#57]
I cannot find the feature flags drop down to activate the extension from the project settings. The documentation isn't clear.

**Comment by joachimdalen** [comment]
Hi! You find the activation under Preview Features - Project. How to find preview features: https://docs.microsoft.com/en-us/azure/devops/project/navigation/preview-features?view=azure-devops&tabs=new-account-enabled#enable-features-for-your-use

**Comment by joachimdalen** [comment]
Improved documentation was now released in `v1.3.1`.
