### ISSUE TITLE
Preview features does not show auto-state

### ISSUE THREAD

**Issue by pablo-vera-dynamo** [joachimdalen/azdevops-auto-state#76]
**Describe the bug**
Preview features does not show auto-state option to enable. This was working some time back, it might be related to the las update.

**To Reproduce**
Go to preview features menu

**Expected behavior**
auto-state option to show

**What version are you on:**
1.4.0 (Latest) 

**Additional context**
--

**Comment by joachimdalen** [comment]
Hi there!

I just did a few checks on my side, and everything looks good here :thinking: 

- Are you trying to enable it for an existing or new project? 
- Are you a Project Administrator in the project you want to enable it? 
- What options do you see in the menu, or is the "For this project" not showing at all?

**Comment by pablo-vera-dynamo** [comment]
Hello, you helped me with the question "What options do you see in the menu, or is the "For this project" not showing at all?"
I was not in a specific project, I was trying to enable it at organization level, when I tried in the project, it worked fine.
thanks
